name: first_passage_times
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - tqdm
  - scipy
  - scikit-survival
  - pip
  - pip:
    - noctiluca
    - bayesmsd
